# The master process listens on a well-known port
# Launched workers connect to the master and redirect their STDOUTs to the same
# Workers can join and leave the cluster on demand.

const HDR_COOKIE_LEN = Distributed.HDR_COOKIE_LEN

@static if Base.VERSION >= v"1.7-"
    # Base.errormonitor() is only available in Julia 1.7+
    my_errormonitor(t) = Base.errormonitor(t)
else
    my_errormonitor(t) = nothing
end

"""
    ElasticManager <: Distributed.ClusterManager

A cluster manager that allows for adding and removing workers dynamically.

Constructor:

```julia
function ElasticManager(;
    addr=IPv4("127.0.0.1"), port=9009, cookie=nothing,
    topology=:all_to_all, manage_callback=elastic_no_op_callback
)
```

The manager will listen for worker connections on `addr:port`. Workers have
to authenticate themselves with `cookie` (randomly generated by default).
`topology` sets the Julia cluster topology and may be `:all_to_all` or
`:master_worker` (see documentation of `Distributed.addprocs` for details).

Workers are not added via `Distributed.addprocs`; instead the user starts
them as separate Julia processes via
[`ElasticClusterManager.elastic_worker`](@ref).

If `manage_callback` is set to a user-provided `my_manage_callback`, it will
be called on the primary Julia process when `Distributed.manage` adds or
removes an elastic worker. The callback signature is

```julia
my_manage_callback(mgr::ElasticManager, id::Integer, :register)
my_manage_callback(mgr::ElasticManager, id::Integer, :deregister)
```

This can be used to automatically add workers to a `Distributed.WorkerPool`,
and so on.

Use `close(em)` to shut the manager down and remove all of its workers
from the cluster.
"""
struct ElasticManager{F} <: Distributed.ClusterManager
    active::Dict{Int, Distributed.WorkerConfig}        # active workers
    pending::Channel{Sockets.TCPSocket}          # to be added workers
    terminated::Set{Int}             # terminated worker ids
    topology::Symbol
    sockname::Tuple{Sockets.IPAddr, UInt16}
    manage_callback::F
    l_sock::Sockets.TCPServer

    function ElasticManager(;
        addr=Sockets.IPv4("127.0.0.1"), port=9009, cookie=nothing,
        topology=:all_to_all, manage_callback=elastic_no_op_callback
    )
        Distributed.init_multi()
        cookie !== nothing && Distributed.cluster_cookie(cookie)

        # Automatically check for the IP address of the local machine
        if addr == :auto
            try
                addr = Sockets.getipaddr(Sockets.IPv4)
            catch
                error("Failed to automatically get host's IP address. Please specify `addr=` explicitly.")
            end
        end

        l_sock = Sockets.listen(addr, port)

        lman = new{typeof(manage_callback)}(
            Dict{Int, Distributed.WorkerConfig}(), Channel{Sockets.TCPSocket}(typemax(Int)),
            Set{Int}(), topology, Sockets.getsockname(l_sock), manage_callback, l_sock
        )

        t1 = @async begin
            while isopen(l_sock)
                s = try
                    Sockets.accept(l_sock)
                catch
                    isopen(l_sock) && rethrow()
                    break
                end
                t2 = @async process_worker_conn(lman, s)
                my_errormonitor(t2)
            end
        end
        my_errormonitor(t1)

        t3 = @async process_pending_connections(lman)
        my_errormonitor(t3)

        lman
    end
end

@deprecate ElasticManager(port) ElasticManager(;port=port)
@deprecate ElasticManager(addr, port) ElasticManager(;addr=addr, port=port)
@deprecate ElasticManager(addr, port, cookie) ElasticManager(;addr=addr, port=port, cookie=cookie)

elastic_no_op_callback(::ElasticManager, ::Integer, ::Symbol) = nothing

function process_worker_conn(mgr::ElasticManager, s::Sockets.TCPSocket)
    @debug "ElasticManager got new worker connection"
    # Validate cookie
    cookie = read(s, HDR_COOKIE_LEN)
    if length(cookie) < HDR_COOKIE_LEN
        close(s)
        error("Cookie read failed. Connection closed by peer.")
    end
    self_cookie = Distributed.cluster_cookie()
    for i in 1:HDR_COOKIE_LEN
        if UInt8(self_cookie[i]) != cookie[i]
            close(s)
            error("Invalid cookie sent by remote worker.")
        end
    end

    try
        put!(mgr.pending, s)
    catch err
        close(s)
        err isa InvalidStateException || rethrow()
    end
end

function process_pending_connections(mgr::ElasticManager)
    while true
        try
            wait(mgr.pending)
        catch err
            err isa InvalidStateException && !isopen(mgr.pending) && break
            rethrow()
        end
        try
            Distributed.addprocs(mgr; topology=mgr.topology)
        catch e
            showerror(stderr, e)
            Base.show_backtrace(stderr, Base.catch_backtrace())
        end
    end
end

"""
    Base.isopen(mgr::ElasticManager)

Return `true` if `mgr` still accepts new worker connections.
"""
Base.isopen(mgr::ElasticManager) = isopen(mgr.l_sock)

"""
    Base.close(mgr::ElasticManager)

Shut down `mgr`: stop accepting new worker connections and remove all of
its active workers from the cluster. Blocks until the workers have been
removed.

Idempotent, closing an already closed manager has no effect.
"""
function Base.close(mgr::ElasticManager)
    close(mgr.l_sock)
    close(mgr.pending)
    while isready(mgr.pending)
        close(take!(mgr.pending))
    end
    isempty(mgr.active) || Distributed.rmprocs(collect(keys(mgr.active)))
    return nothing
end

function Distributed.launch(mgr::ElasticManager, params::Dict, launched::Array, c::Condition)
    # The workers have already been started.
    while isready(mgr.pending)
        @debug "ElasticManager.launch new worker"
        wc=Distributed.WorkerConfig()
        wc.io = take!(mgr.pending)
        push!(launched, wc)
    end

    notify(c)
end

function Distributed.manage(mgr::ElasticManager, id::Integer, config::Distributed.WorkerConfig, op::Symbol)
    if op == :register
        @debug "ElasticManager registering process id $id"
        mgr.active[id] = config
        mgr.manage_callback(mgr, id, op)
    elseif  op == :deregister
        @debug "ElasticManager deregistering process id $id"
        mgr.manage_callback(mgr, id, op)
        delete!(mgr.active, id)
        push!(mgr.terminated, id)
    end
end

function Base.show(io::IO, mgr::ElasticManager)
    println(io, "ElasticManager:")
    println(io, "  Active workers : [", join(sort!(collect(keys(mgr.active))), ", "), "]")
    println(io, "  Number of workers to be added : ", Base.n_avail(mgr.pending))
    println(io, "  Terminated workers : [", join(sort!(collect(mgr.terminated)), ", "), "]")
end

"""
    ElasticClusterManager.elastic_worker(
        cookie::AbstractString, addr::AbstractString="127.0.0.1", port::Integer = 9009;
        forward_stdout::Bool = true, env::AbstractVector = []
    )

Start an elastic worker process that connects to the main Julia process
at IP-address `addr` and port `port`.

Key-value pairs in `env` are added to the worker's environment. If
`forward_stdout` is `true`, the worker's standard output is redirected to
the main process.

Does not return.
"""
function elastic_worker(
    cookie::AbstractString, addr::AbstractString="127.0.0.1", port::Integer = 9009;
    forward_stdout::Bool = true,
    Base.@nospecialize(env::AbstractVector = [],)
)
    @debug "ElasticManager.elastic_worker(cookie, $addr, $port; forward_stdout=$forward_stdout, env=$env)"
    for (k, v) in env
        ENV[k] = v
    end

    c = connect(addr, port)
    write(c, rpad(cookie, HDR_COOKIE_LEN)[1:HDR_COOKIE_LEN])
    if forward_stdout
        redirect_stdout(c)
    end
    Distributed.start_worker(c, cookie)
end

"""
    ElasticClusterManager.worker_start_command(
        em::ElasticManager;
        absolute_exename::Bool = true, same_project::Bool = true, exeflags::Cmd = ``
    )::Cmd

Return a command that starts a Julia process with an elastic worker that
will try to connect to the primary Julia process running the
[`ElasticManager`](@ref) instance `em`.

Use `absolute_exename = false` to use `julia` instead of the full path of
the current Julia executable and `same_project = false` to not activate the
current project. Additional Julia command-line flags can be passed via
`exeflags`.

The returned command should be taken as a baseline. Complex use cases (on
some batch systems, etc.) may require a more involved command.
"""
function worker_start_command(
    em::ElasticManager;
    absolute_exename::Bool = true, same_project::Bool = true, exeflags::Cmd = ``
)
    ip = string(em.sockname[1])
    port = convert(Int, em.sockname[2])
    cookie = Distributed.cluster_cookie()
    exename = absolute_exename ? joinpath(Sys.BINDIR, Base.julia_exename()) : "julia"
    project = same_project ? `--project=$(Pkg.API.Context().env.project_file)` : ``
    code = "import ElasticClusterManager; ElasticClusterManager.elastic_worker(\"$cookie\",\"$ip\",$port)"
    return `$exename $exeflags $project -e $code`
end

"""
    ElasticClusterManager.get_connect_cmd(em::ElasticManager; absolute_exename=true, same_project=true, exeflags::Tuple=())

Like [`worker_start_command`](@ref), but returns the command as a
shell-escaped string, suitable for embedding in job scripts for batch
systems and similar.
"""
function get_connect_cmd(em::ElasticManager; absolute_exename=true, same_project=true, exeflags::Tuple=())
    cmd = worker_start_command(
        em;
        absolute_exename = absolute_exename, same_project = same_project,
        exeflags = Cmd(String[exeflags...])
    )
    return Base.shell_escape_posixly(cmd.exec...)
end
